In [6]:
import torch
import torch.utils.data as Data
torch.manual_seed(6)


## Create Dataset

In [7]:
x = torch.linspace(1,10,10)
y = torch.linspace(10,1,10)
print(x)
print(y)
torch.cat((x.view(len(x),-1),y.view(len(y),-1)),1)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.])


tensor([[ 1., 10.],
        [ 2.,  9.],
        [ 3.,  8.],
        [ 4.,  7.],
        [ 5.,  6.],
        [ 6.,  5.],
        [ 7.,  4.],
        [ 8.,  3.],
        [ 9.,  2.],
        [10.,  1.]])

In [8]:
dataset = Data.TensorDataset(x,y)

## DataLoader

In [9]:
Batch_size = 5

loader =Data.DataLoader(dataset = dataset,
                       batch_size = Batch_size,
                       shuffle = True,
                       num_workers = 1,)

In [10]:
for epoch in range(3):
    for step, (batch_x,batch_y) in enumerate (loader):
        print('Epoch :',epoch ,'| Step ',step,'| batch x :',batch_x.numpy(),'| Batch y: ',batch_y.numpy())

Epoch : 0 | Step  0 | batch x : [ 6.  1. 10.  4.  2.] | Batch y:  [ 5. 10.  1.  7.  9.]
Epoch : 0 | Step  1 | batch x : [7. 3. 5. 8. 9.] | Batch y:  [4. 8. 6. 3. 2.]
Epoch : 1 | Step  0 | batch x : [8. 6. 1. 3. 4.] | Batch y:  [ 3.  5. 10.  8.  7.]
Epoch : 1 | Step  1 | batch x : [ 9. 10.  7.  2.  5.] | Batch y:  [2. 1. 4. 9. 6.]
Epoch : 2 | Step  0 | batch x : [7. 1. 8. 5. 2.] | Batch y:  [ 4. 10.  3.  6.  9.]
Epoch : 2 | Step  1 | batch x : [ 3.  9. 10.  6.  4.] | Batch y:  [8. 2. 1. 5. 7.]


In [11]:
BATCH_SIZE = 8

loader = Data.DataLoader(
                        dataset = dataset,      # torch TensorDataSet format
                        batch_size = BATCH_SIZE, # mini batch size
                        shuffle = True,           # random shuffle for training
                        num_workers = 1,    # subprocesses for loading data
                        )

for epoch in range(3):        #train entire dataset for 3 times
    for step, (batch_x,batch_y) in enumerate (loader):      #for each training step
        
        #train your data
        
        print('Epoch :',epoch ,'| Step ',step,'| batch x :',
              batch_x.numpy(),'| Batch y: ',batch_y.numpy())

Epoch : 0 | Step  0 | batch x : [ 2.  6.  1.  7.  4.  9. 10.  5.] | Batch y:  [ 9.  5. 10.  4.  7.  2.  1.  6.]
Epoch : 0 | Step  1 | batch x : [8. 3.] | Batch y:  [3. 8.]
Epoch : 1 | Step  0 | batch x : [9. 2. 7. 8. 3. 5. 6. 4.] | Batch y:  [2. 9. 4. 3. 8. 6. 5. 7.]
Epoch : 1 | Step  1 | batch x : [ 1. 10.] | Batch y:  [10.  1.]
Epoch : 2 | Step  0 | batch x : [8. 2. 6. 3. 9. 4. 1. 7.] | Batch y:  [ 3.  9.  5.  8.  2.  7. 10.  4.]
Epoch : 2 | Step  1 | batch x : [10.  5.] | Batch y:  [1. 6.]


## Create dataset from Image

In [16]:
import torchvision
import torchvision.datasets as dsets
import torchvision.transforms as transforms

img_dir = "./images"
img_data = dsets.ImageFolder(img_dir,transforms.Compose([
            transforms.RandomResizedCrop(224)
            transforms.ToTensor(),]))
print(img_data.classes)

SyntaxError: invalid syntax (3635189032.py, line 8)