In [2]:
import torch
from torch.autograd import Variable

## torch vs Variable

In [4]:
tensor = torch.rand(2,2,)
x = Variable(tensor , requires_grad=True)

tensor ,x

(tensor([[0.9977, 0.3805],
         [0.1321, 0.6008]]),
 tensor([[0.9977, 0.3805],
         [0.1321, 0.6008]], requires_grad=True))

In [7]:
x.sum() , x.sqrt() , x**2 , x

(tensor(2.1111, grad_fn=<SumBackward0>),
 tensor([[0.9989, 0.6169],
         [0.3634, 0.7751]], grad_fn=<SqrtBackward0>),
 tensor([[0.9954, 0.1448],
         [0.0174, 0.3610]], grad_fn=<PowBackward0>),
 tensor([[0.9977, 0.3805],
         [0.1321, 0.6008]], requires_grad=True))

## Variable

In [8]:
x.data

tensor([[0.9977, 0.3805],
        [0.1321, 0.6008]])

In [9]:
x.requires_grad , x.grad , x.grad_fn, x.volatile

/home/ram/anaconda3/envs/image/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: volatile was removed (Variable.volatile is always False)
  """Entry point for launching an IPython kernel.


(True, None, None, False)

In [11]:
x = Variable(torch.FloatTensor([3]),requires_grad=True)

y = x**3 + 3

z = Variable(torch.FloatTensor([5]))

x.requires_grad ,y.requires_grad, z.requires_grad, y

(True, True, False, tensor([30.], grad_fn=<AddBackward0>))

In [12]:
y.grad_fn.next_functions[0][0]

In [13]:
y.backward()

In [14]:
x,x.grad

(tensor([3.], requires_grad=True), tensor([27.]))

In [15]:
x.grad , x.grad.data.zero_() , x.grad

(tensor([0.]), tensor([0.]), tensor([0.]))

In [16]:
x1 = Variable(torch.ones(2),requires_grad=True)
x2 = Variable(torch.ones(2))

In [17]:
y = x1* 2 +x2
y

tensor([3., 3.], grad_fn=<AddBackward0>)

In [ ]:
y.backward()